name: Compile for Windows

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      
    - name: Restore Nuget Packages
      run: nuget restore Source\visual_studio_2019\Pikifen.sln

    - name: Build app for release
      run: msbuild Source\visual_studio_2019\Pikifen.vcxproj -t:rebuild -verbosity:n -property:Configuration=Release -property:Platform=x64
      
    - name: Publish Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: Pikifen
        path: ${{ github.workspace }}\build\
